# Generated by Django 4.2.20 on 2025-05-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_volunteerprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
    ]
