# Generated by Django 4.2.20 on 2025-05-05 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_opportunity_is_filled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='is_activestart_date',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='is_filled',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 5, 5)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='age_requirement',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 5, 5)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='num_volunteers_needed',
            field=models.IntegerField(),
        ),
    ]
