# Generated by Django 4.2.20 on 2025-05-06 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0009_alter_application_opportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='volunteer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_applications', to='main_app.volunteerprofile'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
