# Generated by Django 4.2.20 on 2025-05-06 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0010_alter_application_volunteer_alter_membership_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_applications', to='main_app.volunteerprofile'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='volunteers/%Y/%m/%d/'),
        ),
    ]
